document.writeln("<div class=\"foot_mar_top\">");
document.writeln("<div class=\"box\">");
document.writeln("<div class=\"foot_info\">");
document.writeln("<ul>");
document.writeln("<li><a href=\"#\">关于我们</a></li>");
document.writeln("<li><a href=\"#\">市场简介</a></li>");
document.writeln("<li><a href=\"#\">市场动态</a></li>");
document.writeln("<li><a href=\"#\">线下活动</a></li>");
document.writeln("</ul>");
document.writeln("<ul>");
document.writeln("<li><a href=\"#\">新手指南</a></li>");
document.writeln("<li><a href=\"user_login.html\">注册新用户</a></li>");
document.writeln("<li><a href=\"#\">雇主入门</a></li>");
document.writeln("<li><a href=\"#\">规则中心</a></li>");
document.writeln("</ul>");
document.writeln("<ul>");
document.writeln("<li><a href=\"#\">服务保障</a></li>");
document.writeln("<li><a href=\"#\">服务流程</a></li>");
document.writeln("<li><a href=\"#\">服务反馈</a></li>");
document.writeln("<li><a href=\"#\">服务监管</a></li>");
document.writeln("</ul>");
document.writeln("<ul>");
document.writeln("<li><a href=\"#\">合作伙伴</a></li>");
document.writeln("<li><a href=\"#\">服务商入驻</a></li>");
document.writeln("<li><a href=\"#\">服务商入驻流程</a></li>");
document.writeln("<li><a href=\"#\">商家管理规范</a></li>");
document.writeln("</ul>");
document.writeln("<ul>");
document.writeln("<li><a href=\"#\">帮助中心</a></li>");
document.writeln("<li><a href=\"#\">常见问题</a></li>");
document.writeln("<li><a href=\"#\">运维服务</a></li>");
document.writeln("<li><a href=\"#\">管理规范</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln(" <div class=\"clear\"></div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\"box copyright\">Copyright 2005-2020 xxx.com 版权所有</div>");
